import type { Lead } from "./types";

// Hand-authored sample leads used to build and preview the dashboard before
// the backend + scraper exist. Typed as `Lead[]`, so TypeScript guarantees
// every record is valid — if the model changes, this file must change too.
//
// The set is deliberately varied: all three venue types (weighted toward the
// client's priority order Restaurants > Bars > Venues), both discovery signals,
// every status (incl. Licensed + Declined), a spread of US cities, 1–3 source
// records each, and a few venue-level notes.

export const MOCK_LEADS: Lead[] = [
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000001",
    name: "Lantern & Vine",
    type: "restaurant",
    streetAddress: "1200 E 6th St",
    city: "Austin",
    state: "TX",
    postalCode: "78702",
    signal: "recently_opened",
    openedDate: "2026-05-12",
    status: "new",
    archived: false,
    discoveredAt: "2026-06-25T07:00:00Z",
    note: "",
    contacts: [],
    sources: [
      {
        id: "src-0001",
        source: "Google Places",
        url: "https://maps.google.com/?cid=lanternandvine",
        discoveredAt: "2026-06-25T07:00:00Z",
      },
      {
        id: "src-0002",
        source: "Yelp",
        url: "https://yelp.com/biz/lantern-and-vine-austin",
        discoveredAt: "2026-06-25T07:01:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0001",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-25T07:00:00Z",
        note: "",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000002",
    name: "The Copper Tap",
    type: "bar",
    streetAddress: "415 Broadway",
    city: "Nashville",
    state: "TN",
    postalCode: "37203",
    signal: "recently_opened",
    openedDate: "2026-04-28",
    status: "reached_out",
    archived: false,
    discoveredAt: "2026-06-20T07:00:00Z",
    note: "",
    contacts: [],
    sources: [
      {
        id: "src-0003",
        source: "Google Places",
        url: "https://maps.google.com/?cid=coppertap",
        discoveredAt: "2026-06-20T07:00:00Z",
      },
      {
        id: "src-0004",
        source: "Eventbrite",
        url: "https://eventbrite.com/e/live-music-copper-tap",
        discoveredAt: "2026-06-21T09:30:00Z",
      },
      {
        id: "src-0005",
        source: "Local News",
        url: "https://nashvillescene.com/copper-tap-opens",
        discoveredAt: "2026-06-22T12:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0002",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-20T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0003",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Kasey",
        changedAt: "2026-06-23T15:42:00Z",
        note: "Called the venue, left a voicemail with the manager.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000003",
    name: "Marisol Cantina",
    type: "restaurant",
    streetAddress: "789 5th Ave",
    city: "San Diego",
    state: "CA",
    postalCode: "92101",
    signal: "pre_opening",
    openedDate: null,
    status: "in_communication",
    archived: false,
    discoveredAt: "2026-06-10T07:00:00Z",
    note: "Owner: Maria. Soft opening mid-July; prefers a follow-up call over email.",
    contacts: [
      {
        id: "ct-0001",
        name: "Maria Delgado",
        role: "Owner",
        phone: "+1 619-555-0142",
        email: "maria@marisolcantina.com",
      },
    ],
    sources: [
      {
        id: "src-0006",
        source: "Public Permit Filing",
        url: "https://sandiego.gov/permits/marisol-cantina",
        discoveredAt: "2026-06-10T07:00:00Z",
      },
      {
        id: "src-0007",
        source: "Local News",
        url: "https://sandiegouniontribune.com/marisol-coming-soon",
        discoveredAt: "2026-06-14T08:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0004",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-10T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0005",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Kasey",
        changedAt: "2026-06-12T10:15:00Z",
        note: "Emailed via the contact form on their teaser site.",
      },
      {
        id: "sc-0006",
        fromStatus: "reached_out",
        toStatus: "in_communication",
        changedBy: "Kasey",
        changedAt: "2026-06-15T11:00:00Z",
        note: "Owner replied, asked us to follow up after their soft opening.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000004",
    name: "Harbor & Oak",
    type: "restaurant",
    streetAddress: "2340 NW Lovejoy St",
    city: "Portland",
    state: "OR",
    postalCode: "97210",
    signal: "recently_opened",
    openedDate: "2026-06-01",
    status: "new",
    archived: false,
    discoveredAt: "2026-06-24T07:00:00Z",
    note: "",
    contacts: [],
    sources: [
      {
        id: "src-0008",
        source: "Yelp",
        url: "https://yelp.com/biz/harbor-and-oak-portland",
        discoveredAt: "2026-06-24T07:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0007",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-24T07:00:00Z",
        note: "",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000005",
    name: "Echo Room",
    type: "venue",
    streetAddress: "1550 Platte St",
    city: "Denver",
    state: "CO",
    postalCode: "80202",
    signal: "pre_opening",
    openedDate: null,
    status: "new",
    archived: false,
    discoveredAt: "2026-06-26T07:00:00Z",
    note: "",
    contacts: [],
    sources: [
      {
        id: "src-0009",
        source: "Public Permit Filing",
        url: "https://denvergov.org/permits/echo-room",
        discoveredAt: "2026-06-26T07:00:00Z",
      },
      {
        id: "src-0010",
        source: "Eventbrite",
        url: "https://eventbrite.com/o/echo-room-denver",
        discoveredAt: "2026-06-26T07:05:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0008",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-26T07:00:00Z",
        note: "",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000006",
    name: "Saltline Oyster Bar",
    type: "bar",
    streetAddress: "64 Market St",
    city: "Charleston",
    state: "SC",
    postalCode: "29401",
    signal: "recently_opened",
    openedDate: "2026-05-20",
    status: "declined",
    archived: false,
    discoveredAt: "2026-06-18T07:00:00Z",
    note: "Declined — owner says their landlord's blanket license already covers live performances. Worth re-checking if they change locations.",
    contacts: [],
    sources: [
      {
        id: "src-0011",
        source: "Google Places",
        url: "https://maps.google.com/?cid=saltline",
        discoveredAt: "2026-06-18T07:00:00Z",
      },
      {
        id: "src-0012",
        source: "Yelp",
        url: "https://yelp.com/biz/saltline-oyster-bar-charleston",
        discoveredAt: "2026-06-18T07:02:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0009",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-18T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0010",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Client",
        changedAt: "2026-06-19T14:00:00Z",
        note: "",
      },
      {
        id: "sc-0015",
        fromStatus: "reached_out",
        toStatus: "declined",
        changedBy: "Client",
        changedAt: "2026-06-21T09:00:00Z",
        note: "Owner declined — already covered under landlord's blanket license.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000007",
    name: "The Greenhouse Social",
    type: "venue",
    streetAddress: "318 Washington Ave N",
    city: "Minneapolis",
    state: "MN",
    postalCode: "55401",
    signal: "recently_opened",
    openedDate: "2026-04-05",
    status: "licensed",
    archived: false,
    discoveredAt: "2026-06-05T07:00:00Z",
    note: "Licensed 6/24. Owner Devon was easy to work with — open to referring other venues in their group.",
    contacts: [
      {
        id: "ct-0002",
        name: "Devon Pierce",
        role: "Owner",
        phone: null,
        email: "devon@greenhousesocial.com",
      },
      {
        id: "ct-0003",
        name: "Tasha Lin",
        role: "Events Manager",
        phone: "+1 612-555-0188",
        email: null,
      },
    ],
    sources: [
      {
        id: "src-0013",
        source: "Eventbrite",
        url: "https://eventbrite.com/o/greenhouse-social",
        discoveredAt: "2026-06-05T07:00:00Z",
      },
      {
        id: "src-0014",
        source: "Local News",
        url: "https://startribune.com/greenhouse-social-opens",
        discoveredAt: "2026-06-06T08:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0011",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-05T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0012",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Kasey",
        changedAt: "2026-06-07T09:00:00Z",
        note: "Reached out through their events booking email.",
      },
      {
        id: "sc-0013",
        fromStatus: "reached_out",
        toStatus: "in_communication",
        changedBy: "Kasey",
        changedAt: "2026-06-09T16:30:00Z",
        note: "Booking manager acknowledged, reviewing internally.",
      },
      {
        id: "sc-0016",
        fromStatus: "in_communication",
        toStatus: "licensed",
        changedBy: "Kasey",
        changedAt: "2026-06-24T10:00:00Z",
        note: "Signed a BMI license — welcome packet sent.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000008",
    name: "Birdie's Diner",
    type: "restaurant",
    streetAddress: "3925 Main St",
    city: "Kansas City",
    state: "MO",
    postalCode: "64111",
    signal: "recently_opened",
    openedDate: "2026-06-08",
    status: "new",
    archived: false,
    discoveredAt: "2026-06-26T07:00:00Z",
    note: "",
    contacts: [],
    sources: [
      {
        id: "src-0015",
        source: "Google Places",
        url: "https://maps.google.com/?cid=birdiesdiner",
        discoveredAt: "2026-06-26T07:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0014",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-06-26T07:00:00Z",
        note: "",
      },
    ],
  },

  // --- Archived leads (archived: true) ------------------------------------
  // Retired from the default dashboard; visible only in the archived view.
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000009",
    name: "Old Town Tavern",
    type: "bar",
    streetAddress: "210 W Broughton St",
    city: "Savannah",
    state: "GA",
    postalCode: "31401",
    signal: "recently_opened",
    openedDate: "2026-01-15",
    status: "licensed",
    archived: true,
    discoveredAt: "2026-02-01T07:00:00Z",
    note: "Licensed back in February. Fully closed out — archived.",
    contacts: [
      {
        id: "ct-0004",
        name: "Front desk",
        role: null,
        phone: "+1 912-555-0110",
        email: null,
      },
    ],
    sources: [
      {
        id: "src-0016",
        source: "Google Places",
        url: "https://maps.google.com/?cid=oldtowntavern",
        discoveredAt: "2026-02-01T07:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0015",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-02-01T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0016",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Kasey",
        changedAt: "2026-02-03T10:00:00Z",
        note: "",
      },
      {
        id: "sc-0017",
        fromStatus: "reached_out",
        toStatus: "licensed",
        changedBy: "Kasey",
        changedAt: "2026-02-10T12:00:00Z",
        note: "Signed and onboarded.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000010",
    name: "Pier 7 Grill",
    type: "restaurant",
    streetAddress: "700 Channelside Dr",
    city: "Tampa",
    state: "FL",
    postalCode: "33602",
    signal: "recently_opened",
    openedDate: "2026-02-20",
    status: "declined",
    archived: true,
    discoveredAt: "2026-03-01T07:00:00Z",
    note: "Declined — corporate handles all licensing centrally. No further action.",
    contacts: [],
    sources: [
      {
        id: "src-0017",
        source: "Yelp",
        url: "https://yelp.com/biz/pier-7-grill-tampa",
        discoveredAt: "2026-03-01T07:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0018",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-03-01T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0019",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Client",
        changedAt: "2026-03-04T09:00:00Z",
        note: "",
      },
      {
        id: "sc-0020",
        fromStatus: "reached_out",
        toStatus: "declined",
        changedBy: "Client",
        changedAt: "2026-03-08T13:30:00Z",
        note: "Corporate covers licensing — dead end.",
      },
    ],
  },
  {
    id: "8f3b1c20-1a2b-4c3d-9e4f-000000000011",
    name: "The Hollow",
    type: "venue",
    streetAddress: "45 Biltmore Ave",
    city: "Asheville",
    state: "NC",
    postalCode: "28801",
    signal: "recently_opened",
    openedDate: "2026-03-12",
    status: "reached_out",
    archived: true,
    discoveredAt: "2026-03-15T07:00:00Z",
    note: "Archived for now — never heard back after two attempts. Revisit in the fall.",
    contacts: [],
    sources: [
      {
        id: "src-0018",
        source: "Eventbrite",
        url: "https://eventbrite.com/o/the-hollow-asheville",
        discoveredAt: "2026-03-15T07:00:00Z",
      },
    ],
    statusHistory: [
      {
        id: "sc-0021",
        fromStatus: null,
        toStatus: "new",
        changedBy: null,
        changedAt: "2026-03-15T07:00:00Z",
        note: "",
      },
      {
        id: "sc-0022",
        fromStatus: "new",
        toStatus: "reached_out",
        changedBy: "Kasey",
        changedAt: "2026-03-17T11:00:00Z",
        note: "Reached out twice, no response.",
      },
    ],
  },
];
